org.gradle.jvmargs=-Xmx4G -Dfile.encoding=UTF-8
org.gradle.parallel=true
org.gradle.configuration-cache=false

# Fabric Properties
minecraft_version=1.21.4
yarn_mappings=1.21.4+build.8
loader_version=0.19.5
loom_version=1.17-SNAPSHOT
fabric_api_version=0.119.4+1.21.4
geckolib_version=4.8.5

# Mod Properties
mod_version=3.0.14
maven_group=westra
archives_base_name=westra
