org.gradle.jvmargs=-Xmx4G -Dfile.encoding=UTF-8
org.gradle.parallel=true
org.gradle.configuration-cache=false

minecraft_version=1.21.4
loader_version=0.16.14
fabric_api_version=0.119.4+1.21.4
mixinextras_version=0.4.1
loom_version=1.10.5

mod_version=1.0.3-recovered
maven_group=org.patch.arbuzhack
archives_base_name=arbuzhack-recovered
